
version: 2

models:
  - name: customers
    description: 'cleaned up table of customers'
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: monthly_new_customers
    description: 'Monthly Count of New Customers'
    columns:
      - name: signup_month
      - name: new_customers