version: 2

sources:
  - name: coffee_shop
    project: analytics-engineers-club
    tags: 
      - coffee
      - practice
    freshness:
      warn_after: {count: 72, period: hour}
      error_after: {count: 96, period: hour}
    tables:
      - name: customers
        descritpion: Customer table.
        columns:
          - name: id
            tests:
              - unique
              - not_null

      - name: orders
        columns:
          - name: id
            descritpion: Orders table.
            tests:
              - unique
              - not_null

      - name: order_items
      - name: product_prices
      - name: products